"""Generated by scripts/extract_ability_pools.py — do not edit by hand.

Source: chaos cache (gen9nationaldexag) | hand-curated fallback,
filtered against poke-env's gen-9 pokedex for authoritative ability
pool data. See scripts/extract_ability_pools.py for the pipeline.
"""
from __future__ import annotations

_LEVITATE_SPECIES: frozenset[str] = frozenset(['azelf', 'baltoy', 'bronzong', 'carnivine', 'chimecho', 'claydol', 'cresselia', 'cryogonal', 'duskull', 'eelektrik', 'eelektross', 'flygon', 'gastly', 'giratinaorigin', 'haunter', 'hydreigon', 'koffing', 'latias', 'latiasmega', 'latios', 'latiosmega', 'lunatone', 'mesprit', 'misdreavus', 'mismagius', 'rotom', 'rotomfan', 'rotomfrost', 'rotomheat', 'rotommow', 'rotomwash', 'solrock', 'tynamo', 'unown', 'uxie', 'vibrava', 'vikavolt', 'weezing', 'weezinggalar'])

_MAGICGUARD_SPECIES: frozenset[str] = frozenset(['alakazam', 'clefable', 'clefairy', 'cleffa', 'duosion', 'kadabra', 'reuniclus', 'sigilyph', 'solosis'])
